### ISSUE TITLE
great tool :D

### ISSUE THREAD

**Issue by dragonGRaf** [ShadowOri/TheIsleSaveNotes#2]
but could u add legacy dinos?
or open source code so people can fork and add legacy?

**Comment by ShadowOri** [comment]
I forgot I made this lol, sure i'll try to add legacy as well

**Comment by dragonGRaf** [comment]
great :D lmk if u have a update

**Comment by ShadowOri** [comment]
I added the legacy dinos, lmk if there's anything else i should do :D

**Comment by dragonGRaf** [comment]
10/10 thank you :D i will let u know if i have other ideas or bugs etc
